#!/usr/bin/env node

/**
 * Simple build script that concatenates our modular source files
 * into the single files expected by the existing GitHub workflow.
 *
 * This approach maintains full backward compatibility while enabling
 * clean development structure.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Build configuration
const BUILD_CONFIG = {
  components: [
    'historical-data-loader.js',
    'taiko-simulator-js.js',
    'metrics-framework-js.js',
    'simulator.js',
    'charts.js',
    'pareto-visualizer.js',
    'nsga-ii-web.js',
    'optimization-research.js',
    'app.js'
  ],
  outputDir: '../',  // Output to root level where workflow expects
};

function readComponent(filename) {
  const filePath = path.join(__dirname, 'components', filename);
  if (fs.existsSync(filePath)) {
    const content = fs.readFileSync(filePath, 'utf8');
    return `\n// === ${filename} ===\n${content}\n`;
  } else {
    console.warn(`⚠️  Component not found: ${filename}`);
    return '';
  }
}

function buildApplication() {
  console.log('🏗️  Building Taiko Fee Mechanism Explorer...');

  // Concatenate all components in the correct order
  let appJs = '// Built from web_src/ - DO NOT EDIT DIRECTLY\n';
  appJs += '// This file is generated by web_src/build.js\n';

  for (const component of BUILD_CONFIG.components) {
    appJs += readComponent(component);
  }

  // Copy CSS
  const cssSource = path.join(__dirname, 'styles/styles.css');
  const cssTarget = path.join(__dirname, BUILD_CONFIG.outputDir, 'styles.css');

  if (fs.existsSync(cssSource)) {
    fs.copyFileSync(cssSource, cssTarget);
    console.log('✅ Copied styles.css');
  }

  // Copy HTML
  const htmlSource = path.join(__dirname, 'index.html');
  const htmlTarget = path.join(__dirname, BUILD_CONFIG.outputDir, 'index.html');

  let htmlContent = fs.readFileSync(htmlSource, 'utf8');

  // Update paths for production
  htmlContent = htmlContent.replace('href="styles/styles.css"', 'href="styles.css"');
  htmlContent = htmlContent.replace('<script type="module" src="main.js"></script>',
    `<script src="app.js"></script>`);

  fs.writeFileSync(htmlTarget, htmlContent);
  console.log('✅ Generated index.html');

  // Write the concatenated JavaScript
  const jsTarget = path.join(__dirname, BUILD_CONFIG.outputDir, 'app.js');
  fs.writeFileSync(jsTarget, appJs);
  console.log('✅ Generated app.js');

  // Show what was built
  const stats = fs.statSync(jsTarget);
  console.log(`📊 Built app.js: ${Math.round(stats.size / 1024)}KB`);
  console.log('🎉 Build complete! Files ready for GitHub workflow.');
}

buildApplication();